### ISSUE TITLE
Conflict with Themes (Seti Monokai)

### ISSUE THREAD

**Issue by mkormendy** [SublimeText/InactivePanes#15]
First off, I don't expect you to support every theme configuration out there .. but I do believe there is a path issue with the way that InactivePanes stores the backup scheme in that it creates a duplicate file structure of the theme under the InactivePanes folder.

![screen shot 2017-07-20 at 8 37 15 am](https://user-images.githubusercontent.com/1437667/28420158-d5859e66-6d26-11e7-80e4-77887a238546.png)

Why not just store a renamed backup in the same directory as the theme?

**Comment by FichteFoll** [comment]
This is intended, because the original source may not be writable, for example when it's inside a `.sublime-package` archive. I also do not want to modify a user's files in-place, so a copy of the file is an absolute must.

Mirroring the folder structure was a design choice with the advantage of collision-prevention in case of color scheme files with the same name. SublimeLinter, for example, stores all its modified color scheme in the User/SublimeLinter folder, flat.

However, I have the feeling that this isn't exactly what you wanted to hear. Maybe you can explain *why* you believe this is an issue?

**Comment by mkormendy** [comment]
All good points.
