### ISSUE TITLE
Enhancement: ability to change the line highlight color for inactive panes?

### ISSUE THREAD

**Issue by jamesderlin** [SublimeText/InactivePanes#16]
From: https://forum.sublimetext.com/t/is-there-any-way-to-highlight-the-current-line-only-in-the-focused-group/34802

Would it be possible for InactivePanes to provide an option to change the line highlight color for inactive panes?

**Comment by jamesderlin** [comment]
... But now I realize that InactivePanes will regenerate its `.tmTheme` file whenever SublimeText starts up.  Argh.

But at least now I know it's possible, so maybe I'll see if I can implement this myself.

**Comment by FichteFoll** [comment]
I have started a rewrite a while ago but haven't made much progress in recent time. The rewrite is needed because of the new `.sublime-color-scheme` format that requires a different approach for modifying colors, but that would also allow you to specify an override file for the inactive scheme specifically because its name will be deterministic and the new format supports overrides natively.

**Comment by FichteFoll** [comment]
The package has been deprecated and the functionality has been implemented natively into Sublime Text 4. Refer to the [readme](https://github.com/SublimeText/InactivePanes#readme) for instructions if you don't already use the new feature.

---

Unfortunately, the feature requested here is not available in the native implementation but I have no intention of providing a solution for it.
