### ISSUE TITLE
Warning prevents me from using sublime text or uninstall InactivePanes

### ISSUE THREAD

**Issue by aless80** [SublimeText/InactivePanes#22]
I just installed this package and a warning keeps on popping up so that I cannot run or uninstall InactivePanes anymore. The warning says that my color scheme settings (Monokai.sublime-color-scheme) is not supported. The warning should not keep on popping up. 
![Selection_002](https://user-images.githubusercontent.com/6652854/171341556-b91564a0-e6f1-4c64-a7c2-bbd324a8ef67.png)

**Comment by FichteFoll** [comment]
Ugh, that's unfortunate. I was hoping to just deprecate the package silently, but I suppose I should push an update message with that anyway for people unaware of the new built-in functionality.

I'll prepare an update that prevents this from happening and then officially deprecate the package when I find the time.

**Comment by SanJacobs** [comment]
I just had this same problem, a real nuke of an issue.

**Comment by FichteFoll** [comment]
Sorry for the mess it caused. I have fixed the issue and added deprecation notices at various points. The package still works for tmTheme files (just tested it again), but it's still the same rough experience when switching color schemes and obviously never worked for the new scheme format, which is why you can still install it if you really want to, but I'm not gonna work on it any more.

I'll archive the repository in a short while (whenever I remember it, probably) to make this even more obvious.
